# Generated by Django 3.2.4 on 2021-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/%Y/%M/%D/'),
        ),
    ]
