# Generated by Django 3.2.4 on 2021-06-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_formation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.ImageField(blank=True, default='logo/default.jpg', null=True, upload_to='logos'),
        ),
    ]
