# Generated by Django 3.2.4 on 2021-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_formation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
