# Generated by Django 3.2.4 on 2021-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_formation_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
