# Generated by Django 3.2.4 on 2021-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_formation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='etat',
            field=models.CharField(choices=[('activé', 'activé'), ('non activé', 'non activé')], max_length=200, null=True),
        ),
    ]
